CREATE TABLE DIM_SUSCRIPCION(
	SUSCRIPCIONID INT,
	TIPO_SUSCRIPCION VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY(SUSCRIPCIONID)
);

CREATE TABLE DIM_SUSCRIPTOR(
	SUSCRIPTORID INT,
	GENERO VARCHAR2(1) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	CONSTRAINT PK_SUSCRIPTOR PRIMARY KEY(SUSCRIPTORID)
);

CREATE TABLE DIM_TIEMPO(
	TIEMPOID INT,
	ANIO INT NOT NULL,
	TRIMESTRE INT NOT NULL,
	MES INT NOT NULL,
	CONSTRAINT PK_TIEMPO PRIMARY KEY(TIEMPOID)
);

CREATE TABLE DIM_DISPOSITIVO(
	DISPOSITIVOID INT,
	NOMBRE VARCHAR2(50),
	CONSTRAINT PK_DISPOSITIVO PRIMARY KEY(DISPOSITIVOID)
);

CREATE TABLE DIM_UBICACION(
	UBICACIONID INT,
	NOMBRE VARCHAR2(150),
	CONSTRAINT PK_UBICACION PRIMARY KEY(UBICACIONID)
);

CREATE TABLE FACT_INGRESOS (
	INGRESOSSUSCRIPCIONID INT,
	SUSCRIPCIONID INT NOT NULL,
	SUSCRIPTORID INT,
	DISPOSITIVOID INT NOT NULL,
	UBICACIONID INT NOT NULL,
	TIEMPOID INT NOT NULL,
	TOTALINGRESOSSUSCRIPCION NUMBER(10, 2) NOT NULL,
	CONSTRAINT PK_INGRESOS_SUSCRIPCION PRIMARY KEY(INGRESOSSUSCRIPCIONID, SUSCRIPCIONID, SUSCRIPTORID, DISPOSITIVOID, UBICACIONID, TIEMPOID),
	CONSTRAINT FK_INGRESOS_SUSCRIPCION FOREIGN KEY(SUSCRIPCIONID) REFERENCES DIM_SUSCRIPCION(SUSCRIPCIONID),
	CONSTRAINT FK_INGRESOS_SUSCRIPTOR FOREIGN KEY(SUSCRIPTORID) REFERENCES DIM_SUSCRIPTOR(SUSCRIPTORID),
	CONSTRAINT FK_INGRESOS_DISPOSITIVO FOREIGN KEY(DISPOSITIVOID) REFERENCES DIM_DISPOSITIVO(DISPOSITIVOID),
	CONSTRAINT FK_INGRESOS_UBICACION FOREIGN KEY(UBICACIONID) REFERENCES DIM_UBICACION(UBICACIONID),
	CONSTRAINT FK_INGRESOS_TIEMPO FOREIGN KEY(TIEMPOID) REFERENCES DIM_TIEMPO(TIEMPOID)
);

CREATE TABLE ETL_LOG (
	LOG_ID NUMBER PRIMARY KEY,
	PROCEDURE_NAME VARCHAR2(100),
	EXECUTION_DATE DATE,
	SUCCESS_VALUE CHAR(1) CHECK (SUCCESS_VALUE IN ('Y', 'N')),
	ERROR_MESSAGE VARCHAR2(500)
);