--Formulario para las suscripciones

CREATE OR REPLACE PROCEDURE CrearSuscripcion(
    ID_SUSCRIPTOR IN TBL_SUSCRIPTORES.ID_SUSCRIPTOR%TYPE,
    NOMBRE IN TBL_SUSCRIPTORES.NOMBRE%TYPE,
    APELLIDOS IN TBL_SUSCRIPTORES.APELLIDOS%TYPE,
    FECHA_NACIMIENTO IN TBL_SUSCRIPTORES.FECHA_NACIMIENTO%TYPE,
    GENERO IN TBL_SUSCRIPTORES.GENERO%TYPE,
    DIRECCION IN TBL_SUSCRIPTORES.DIRECCION%TYPE,
    NUMERO_CELULAR IN TBL_SUSCRIPTORES.NUMERO_CELULAR%TYPE,
    CORREO IN TBL_SUSCRIPTORES.CORREO%TYPE,
    CONTRASENIA IN TBL_SUSCRIPTORES.CONTRASENIA%TYPE,
    ID_SUSCRIPCION IN TBL_SUSCRIPCIONES.ID_SUSCRIPCION%TYPE,
    DESCRIPCION IN TBL_SUSCRIPCIONES.DESCRIPCION%TYPE,
    TIPO IN TBL_SUSCRIPCIONES.TIPO%TYPE,
    FECHA_INICIO IN TBL_SUSCRIPCIONES.FECHA_INICIO%TYPE,
    FECHA_FIN IN TBL_SUSCRIPCIONES.FECHA_FIN%TYPE,
    PRECIO IN TBL_SUSCRIPCIONES.PRECIO%TYPE,
    ID_SUSCRIPTOR IN TBL_SUSCRIPCIONES.ID_SUSCRIPTOR%TYPE
)
AS
BEGIN
    INSERT INTO TBL_SUSCRIPTORES (ID_SUSCRIPTOR, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, GENERO, DIRECCION, NUMERO_CELULAR, CORREO, CONTRASENIA)
    VALUES (ID_SUSCRIPTOR,NOMBRE, APELLIDOS, FECHA_NACIMIENTO, GENERO, DIRECCION, NUMERO_CELULAR, CORREO, CONTRASENIA);
    INSERT INTO TBL_SUSCRIPCIONES (ID_SUSCRIPCION, DESCRIPCION, TIPO, FECHA_INICIO, FECHA_FIN, PRECIO, ID_SUSCRIPTOR)
    VALUES (ID_SUSCRIPCION, DESCRIPCION, TIPO, FECHA_INICIO, FECHA_FIN, PRECIO, ID_SUSCRIPTOR);
    COMMIT;
    
END;




CREATE OR REPLACE PROCEDURE BuscarSuscriptor(
    P_ID_SUSCRIPTOR IN TBL_SUSCRIPTORES.ID_SUSCRIPTOR%TYPE,
    P_NOMBRE OUT TBL_SUSCRIPTORES.NOMBRE%TYPE,
    P_APELLIDOS OUT TBL_SUSCRIPTORES.APELLIDOS%TYPE,
    P_FECHA_NACIMIENTO OUT TBL_SUSCRIPTORES.FECHA_NACIMIENTO%TYPE,
    P_GENERO OUT TBL_SUSCRIPTORES.GENERO%TYPE,
    P_DIRECCION OUT TBL_SUSCRIPTORES.DIRECCION%TYPE,
    P_NUMERO_CELULAR OUT TBL_SUSCRIPTORES.NUMERO_CELULAR%TYPE,
    P_CORREO OUT TBL_SUSCRIPTORES.CORREO%TYPE,
    P_ID_SUSCRIPCION IN TBL_SUSCRIPCIONES.ID_SUSCRIPCION%TYPE,
    P_DESCRIPCION OUT TBL_SUSCRIPCIONES.DESCRIPCION%TYPE,
    P_TIPO OUT TBL_SUSCRIPCIONES.TIPO%TYPE,
    P_FECHA_INICIO OUT TBL_SUSCRIPCIONES.FECHA_INICIO%TYPE,
    P_FECHA_FIN OUT TBL_SUSCRIPCIONES.FECHA_FIN%TYPE,
    P_PRECIO OUT TBL_SUSCRIPCIONES.PRECIO%TYPE
)
AS
BEGIN
    SELECT TBL_SUSCRIPTORES.NOMBRE,TBL_SUSCRIPTORES.APELLIDOS, TBL_SUSCRIPTORES.FECHA_NACIMIENTO, 
    TBL_SUSCRIPTORES.GENERO, TBL_SUSCRIPTORES.DIRECCION, TBL_SUSCRIPTORES.NUMERO_CELULAR, TBL_SUSCRIPTORES.CORREO, 
    TBL_SUSCRIPCIONES.DESCRIPCION, TBL_SUSCRIPCIONES.TIPO, TBL_SUSCRIPCIONES.FECHA_INICIO, TBL_SUSCRIPCIONES.FECHA_FIN, TBL_SUSCRIPCIONES.PRECIO
    INTO P_NOMBRE,P_APELLIDOS, P_FECHA_NACIMIENTO, P_GENERO, P_DIRECCION, P_NUMERO_CELULAR, P_CORREO, P_DESCRIPCION, P_TIPO, P_FECHA_INICIO, P_FECHA_FIN, P_PRECIO
    FROM TBL_SUSCRIPTORES
    INNER JOIN TBL_SUSCRIPCIONES
    ON tbl_suscriptores.id_suscriptor = tbl_suscripciones.id_suscriptor
    WHERE tbl_suscriptores.id_suscriptor=P_ID_SUSCRIPTOR;
    
END;




CREATE OR REPLACE PROCEDURE ActualizarSuscripcion(
    P_ID_SUSCRIPTOR IN TBL_SUSCRIPTORES.ID_SUSCRIPTOR%TYPE,
    P_NOMBRE IN TBL_SUSCRIPTORES.NOMBRE%TYPE,
    P_APELLIDOS IN TBL_SUSCRIPTORES.APELLIDOS%TYPE,
    P_FECHA_NACIMIENTO IN TBL_SUSCRIPTORES.FECHA_NACIMIENTO%TYPE,
    P_GENERO IN TBL_SUSCRIPTORES.GENERO%TYPE,
    P_DIRECCION IN TBL_SUSCRIPTORES.DIRECCION%TYPE,
    P_NUMERO_CELULAR IN TBL_SUSCRIPTORES.NUMERO_CELULAR%TYPE,
    P_CORREO IN TBL_SUSCRIPTORES.CORREO%TYPE,
    P_CONTRASENIA IN TBL_SUSCRIPTORES.CONTRASENIA%TYPE,
    P_ID_SUSCRIPCION IN TBL_SUSCRIPCIONES.ID_SUSCRIPCION%TYPE,
    P_DESCRIPCION IN TBL_SUSCRIPCIONES.DESCRIPCION%TYPE,
    P_TIPO IN TBL_SUSCRIPCIONES.TIPO%TYPE,
    P_FECHA_INICIO IN TBL_SUSCRIPCIONES.FECHA_INICIO%TYPE,
    P_FECHA_FIN IN TBL_SUSCRIPCIONES.FECHA_FIN%TYPE,
    P_PRECIO IN TBL_SUSCRIPCIONES.PRECIO%TYPE
)
AS
BEGIN
    UPDATE TBL_SUSCRIPTORES SET NOMBRE=P_NOMBRE,
    APELLIDOS=P_APELLIDOS, 
    FECHA_NACIMIENTO=P_FECHA_NACIMIENTO, 
    GENERO=P_GENERO, 
    DIRECCION=P_DIRECCION, 
    NUMERO_CELULAR=P_NUMERO_CELULAR, 
    CORREO=P_CORREO, 
    CONTRASENIA=P_CONTRASENIA
    WHERE ID_SUSCRIPTOR=P_ID_SUSCRIPTOR;

    UPDATE TBL_SUSCRIPCIONES SET DESCRIPCION=P_DESCRIPCION,
    TIPO=P_TIPO, 
    FECHA_INICIO=P_FECHA_INICIO, 
    FECHA_FIN =P_FECHA_FIN,
    PRECIO =P_PRECIO
    WHERE ID_SUSCRIPCION=P_ID_SUSCRIPCION;
    COMMIT;
    
END;


--Formulario para los pagos
CREATE OR REPLACE PROCEDURE CrearPago(
    P_ID_PAGO IN TBL_PAGOS.ID_PAGO%TYPE, 
    P_FECHA IN TBL_PAGOS.FECHA%TYPE, 
    P_MONTO IN TBL_PAGOS.MONTO%TYPE, 
    P_ID_SUSCRIPTOR IN TBL_PAGOS.ID_SUSCRIPTOR%TYPE
)
AS
BEGIN
    INSERT INTO TBL_PAGOS (ID_PAGO, FECHA, MONTO, ID_SUSCRIPTOR)
    VALUES (P_ID_PAGO, P_FECHA, P_MONTO, P_ID_SUSCRIPTOR);
    COMMIT;
END;




CREATE OR REPLACE PROCEDURE ActualizarPago(
    P_ID_PAGO IN TBL_PAGOS.ID_PAGO%TYPE, 
    P_FECHA IN TBL_PAGOS.FECHA%TYPE, 
    P_MONTO IN TBL_PAGOS.MONTO%TYPE, 
    P_ID_SUSCRIPTOR IN TBL_PAGOS.ID_SUSCRIPTOR%TYPE
)
AS
BEGIN
    UPDATE TBL_PAGOS SET FECHA=P_FECHA, MONTO=P_MONTO, ID_SUSCRIPTOR=P_ID_SUSCRIPTOR
    WHERE ID_PAGO=P_ID_PAGO;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE LeerPago(
    P_ID_PAGO IN TBL_PAGOS.ID_PAGO%TYPE, 
    P_FECHA OUT TBL_PAGOS.FECHA%TYPE, 
    P_MONTO OUT TBL_PAGOS.MONTO%TYPE, 
    P_ID_SUSCRIPTOR OUT TBL_PAGOS.ID_SUSCRIPTOR%TYPE
)
AS
BEGIN
    SELECT FECHA, MONTO, ID_SUSCRIPTOR
    INTO  P_FECHA, P_MONTO, P_ID_SUSCRIPTOR
    FROM TBL_PAGOS
    WHERE ID_PAGO=P_ID_PAGO;
    
END;



--Formulario para las categorias
CREATE OR REPLACE PROCEDURE CrearCategoria(
    P_ID_CATEGORIA IN TBL_CATEGORIAS.ID_CATEGORIA%TYPE, 
    P_NOMBRE IN TBL_CATEGORIAS.NOMBRE%TYPE
)
AS
BEGIN
    INSERT INTO TBL_CATEGORIAS (ID_CATEGORIA, NOMBRE)
    VALUES (P_ID_CATEGORIA, P_NOMBRE);
    COMMIT;
END;




CREATE OR REPLACE PROCEDURE ActualizarCategoria(
    P_ID_CATEGORIA IN TBL_CATEGORIAS.ID_CATEGORIA%TYPE, 
    P_NOMBRE IN TBL_CATEGORIAS.NOMBRE%TYPE
)
AS
BEGIN
    UPDATE TBL_CATEGORIAS SET  NOMBRE=P_NOMBRE
    WHERE ID_CATEGORIA=P_ID_CATEGORIA;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE LeerCategoria(
    P_ID_CATEGORIA IN TBL_CATEGORIAS.ID_CATEGORIA%TYPE, 
    P_NOMBRE OUT TBL_CATEGORIAS.NOMBRE%TYPE
)
AS
BEGIN
    SELECT  NOMBRE
    INTO   P_NOMBRE
    FROM TBL_CATEGORIAS
    WHERE ID_CATEGORIA=P_ID_CATEGORIA;
    
END;


-----Formulario para registrar una tajeta
CREATE OR REPLACE PROCEDURE RegistrarTarjeta(
    P_ID_TARJETA IN TBL_TARJETAS.ID_TARJETA%TYPE,
    P_NUM_TARJETA IN TBL_TARJETAS.NUM_TARJETA%TYPE,
    P_TITULAR IN TBL_TARJETAS.TITULAR%TYPE,
    P_FECHA_VENCIMIENTO IN TBL_TARJETAS.FECHA_VENCIMIENTO%TYPE,
    P_PIN IN TBL_TARJETAS.PIN%TYPE,
    P_TIPO IN TBL_TARJETAS.TIPO%TYPE,
    P_ID_SUSCRIPTOR IN TBL_SUSCRIPCION_TARJETA.ID_SUSCRIPTOR%TYPE,
    P_FECHA_VINCULACION IN TBL_SUSCRIPCION_TARJETA.FECHA_VINCULACION%TYPE
)
AS
BEGIN
    INSERT INTO TBL_TARJETAS (ID_TARJETA, NUM_TARJETA, TITULAR, FECHA_VENCIMIENTO, PIN, TIPO)
    VALUES (P_ID_TARJETA, P_NUM_TARJETA, P_TITULAR, P_FECHA_VENCIMIENTO, P_PIN, P_TIPO);
    INSERT INTO TBL_SUSCRIPCION_TARJETA (ID_TARJETA, ID_SUSCRIPTOR, FECHA_VINCULACION, FECHA_DESVINCULACION )
    VALUES (P_ID_TARJETA, P_ID_SUSCRIPTOR, P_FECHA_VINCULACION, null);
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE LeerTarjeta(
    P_ID_TARJETA IN TBL_TARJETAS.ID_TARJETA%TYPE,
    P_NUM_TARJETA OUT TBL_TARJETAS.NUM_TARJETA%TYPE,
    P_TITULAR OUT TBL_TARJETAS.TITULAR%TYPE,
    P_FECHA_VENCIMIENTO OUT TBL_TARJETAS.FECHA_VENCIMIENTO%TYPE,
    P_PIN OUT TBL_TARJETAS.PIN%TYPE,
    P_TIPO OUT TBL_TARJETAS.TIPO%TYPE,
    P_ID_SUSCRIPTOR OUT TBL_SUSCRIPCION_TARJETA.ID_SUSCRIPTOR%TYPE,
    P_FECHA_VINCULACION OUT TBL_SUSCRIPCION_TARJETA.FECHA_VINCULACION%TYPE
)
AS
BEGIN
    SELECT  T.NUM_TARJETA, T.TITULAR, T.FECHA_VENCIMIENTO, T.PIN, T.TIPO,TS.ID_SUSCRIPTOR, TS.FECHA_VINCULACION 
    INTO  P_NUM_TARJETA, P_TITULAR, P_FECHA_VENCIMIENTO, P_PIN, P_TIPO, P_ID_SUSCRIPTOR, P_FECHA_VINCULACION
    FROM TBL_TARJETAS T
    INNER JOIN TBL_SUSCRIPCION_TARJETA TS
    ON T.ID_TARJETA=TS.ID_TARJETA
    WHERE T.ID_TARJETA=P_ID_TARJETA;
END;




---Formulario para crear un ticket de soporte técnico
CREATE OR REPLACE PROCEDURE CrearTicket(
    
    P_ID_TICKET IN TBL_TICKETS_SOPORTE.ID_TICKET%TYPE,
    P_FECHA_CREACION IN TBL_TICKETS_SOPORTE.FECHA_CREACION%TYPE,
    P_DESCRIPCION IN TBL_TICKETS_SOPORTE.DESCRIPCION%TYPE,
    P_PRIORIDAD IN TBL_TICKETS_SOPORTE.PRIORIDAD%TYPE,
    P_ESTADO IN TBL_TICKETS_SOPORTE.ESTADO%TYPE,
    P_DNI_EMPLEADO IN TBL_TICKETS_SOPORTE.DNI_EMPLEADO%TYPE,
    P_ID_SUSCRIPTOR IN TBL_TICKETS_SOPORTE.ID_SUSCRIPTOR%TYPE
    
)
AS
BEGIN
    INSERT INTO TBL_TICKETS_SOPORTE (ID_TICKET, FECHA_CREACION, DESCRIPCION, PRIORIDAD, ESTADO, DNI_EMPLEADO, ID_SUSCRIPTOR)
    VALUES (P_ID_TICKET, P_FECHA_CREACION, P_DESCRIPCION, P_PRIORIDAD, P_ESTADO, P_DNI_EMPLEADO, P_ID_SUSCRIPTOR);
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE ActualizarTicket(
    P_ID_TICKET IN TBL_TICKETS_SOPORTE.ID_TICKET%TYPE,
    P_PRIORIDAD IN TBL_TICKETS_SOPORTE.PRIORIDAD%TYPE,
    P_ESTADO IN TBL_TICKETS_SOPORTE.ESTADO%TYPE,
    P_DNI_EMPLEADO IN TBL_TICKETS_SOPORTE.DNI_EMPLEADO%TYPE
)
AS
BEGIN
    UPDATE TBL_TICKETS_SOPORTE
    SET  PRIORIDAD= P_PRIORIDAD, ESTADO=P_ESTADO, DNI_EMPLEADO=P_DNI_EMPLEADO
    WHERE ID_TICKET = P_ID_TICKET;
    COMMIT;
END;



CREATE OR REPLACE PROCEDURE LeerTicket(
    P_ID_TICKET IN TBL_TICKETS_SOPORTE.ID_TICKET%TYPE,
    P_FECHA_CREACION OUT TBL_TICKETS_SOPORTE.FECHA_CREACION%TYPE,
    P_DESCRIPCION OUT TBL_TICKETS_SOPORTE.DESCRIPCION%TYPE,
    P_PRIORIDAD OUT TBL_TICKETS_SOPORTE.PRIORIDAD%TYPE,
    P_ESTADO OUT TBL_TICKETS_SOPORTE.ESTADO%TYPE,
    P_DNI_EMPLEADO OUT TBL_TICKETS_SOPORTE.DNI_EMPLEADO%TYPE,
    P_ID_SUSCRIPTOR OUT TBL_TICKETS_SOPORTE.ID_SUSCRIPTOR%TYPE
)
AS
BEGIN
    SELECT FECHA_CREACION, DESCRIPCION, PRIORIDAD, ESTADO, DNI_EMPLEADO, ID_SUSCRIPTOR
    INTO  P_FECHA_CREACION, P_DESCRIPCION, P_PRIORIDAD, P_ESTADO, P_DNI_EMPLEADO, P_ID_SUSCRIPTOR
    FROM TBL_TICKETS_SOPORTE
    WHERE ID_TICKET = P_ID_TICKET;
END;




